<script setup lang="ts">
import { computed, onMounted, ref } from "vue"; import { useRouter } from "vue-router"; import type { CategoryItem, PublishedGameSummary } from "@arcade/shared"; import { getCatalogHome } from "../services/api"; import { readFavorites, readRecent, rememberRecent, toggleFavorite } from "../services/portalStorage"; import CategoryChipList from "../components/portal/CategoryChipList.vue"; import FeaturedGameCarousel from "../components/portal/FeaturedGameCarousel.vue"; import GameGrid from "../components/portal/GameGrid.vue"; import RecentGamesSection from "../components/portal/RecentGamesSection.vue"; import ContentStatePanel from "../components/portal/ContentStatePanel.vue"; import PortalSearchBar from "../components/portal/PortalSearchBar.vue";
const router = useRouter(); const loading = ref(true); const error = ref(""); const legacy = ref(false); const categories = ref<CategoryItem[]>([]); const featured = ref<PublishedGameSummary[]>([]); const popular = ref<PublishedGameSummary[]>([]); const newest = ref<PublishedGameSummary[]>([]); const editor = ref<PublishedGameSummary[]>([]); const recent = ref<PublishedGameSummary[]>([]); const favorites = ref<string[]>([]); const fallbackCategories: CategoryItem[] = [];
const allRecent = computed(() => { const slugs = readRecent().values; return slugs.map((slug) => [...popular.value, ...newest.value].find((game) => game.slug === slug)).filter((game): game is PublishedGameSummary => Boolean(game)); });
function favorite(slug: string): void { favorites.value = toggleFavorite(slug).values; }
function play(slug: string): void { rememberRecent(slug); void router.push(`/zh/game/${slug}/play`); }
async function load(): Promise<void> { loading.value = true; error.value = ""; try { const data = await getCatalogHome(); legacy.value = data.legacy_fallback; categories.value = data.categories; featured.value = data.featured; popular.value = data.popular; newest.value = data.new_games; editor.value = data.editor_picks; recent.value = data.recent; } catch { error.value = "首页内容暂时无法加载，请重试。"; } finally { loading.value = false; } }
onMounted(() => { favorites.value = readFavorites().values; void load(); document.title = "星屿游廊｜发现原创网页游戏"; });
</script>
<template><div class="portal-page portal-home-page"><section class="portal-hero"><div><span class="portal-eyebrow">STAR ISLE ARCADE</span><h1>今天，打开一款<br /><em>值得玩的游戏</em></h1><p>轻量、原创、无需安装。按兴趣发现下一段短暂而明亮的旅程。</p></div><PortalSearchBar /></section><p v-if="legacy" class="fallback-notice">当前展示的是旧目录兼容数据；门户后端尚未接通，启动票据不会被客户端伪造。</p><ContentStatePanel v-if="loading" kind="loading" title="正在整理今日内容" message="为你准备推荐、分类和新游。" /><ContentStatePanel v-else-if="error" kind="error" title="首页暂时不可用" :message="error" action="重新加载" @action="load" /><template v-else><section class="portal-section"><div class="portal-section-heading"><div><span class="portal-eyebrow">按兴趣挑选</span><h2>快速分类</h2></div><RouterLink to="/zh/games">全部分类</RouterLink></div><CategoryChipList :categories="categories.length ? categories : fallbackCategories" /></section><section v-if="featured.length" class="portal-section"><div class="portal-section-heading"><div><span class="portal-eyebrow">今日焦点</span><h2>主推荐</h2></div></div><FeaturedGameCarousel :games="featured" :favorite="favorites" @favorite="favorite" @play="play" /></section><section class="portal-section"><div class="portal-section-heading"><div><span class="portal-eyebrow">玩家正在打开</span><h2>热门游戏</h2></div><RouterLink to="/zh/popular">查看榜单</RouterLink></div><GameGrid :games="popular.slice(0, 6)" :favorites="favorites" @favorite="favorite" @play="play" /></section><section class="portal-section"><div class="portal-section-heading"><div><span class="portal-eyebrow">刚刚上新</span><h2>新游</h2></div><RouterLink to="/zh/new">更多新游</RouterLink></div><GameGrid :games="newest.slice(0, 6)" :favorites="favorites" @favorite="favorite" @play="play" /></section><section class="editor-placeholder"><span class="portal-eyebrow">编辑精选 · 即将上线</span><h2>下一期专题正在制作</h2><p>我们会用原创主题串起更多值得反复打开的作品。</p><RouterLink class="portal-secondary-button" to="/zh/about">了解平台理念</RouterLink></section><RecentGamesSection :games="recent.length ? recent : allRecent" :favorites="favorites" @favorite="favorite" @play="play" /></template></div></template>
